services:
  # 1. BANCO DE DADOS
  velo-postgres:
    image: postgres:15-alpine
    container_name: velo-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=velo_trips,velo_identity 
    volumes:
      - velo-db-data:/var/lib/postgresql/data
    networks:
      - velo-network

  # 2. MICROSERVIÇO TRIP MATCHING (NestJS)
  trip-matching:
    build:
      context: ../Velo-trip-matching-service
      dockerfile: Dockerfile
    container_name: velo-trip-matching
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@velo-postgres:5432/velo_trips?schema=public
    depends_on:
      - velo-postgres
    networks:
      - velo-network

  # 3. MICROSERVIÇO IDENTITY DRIVER (PHP / Laravel)
  identity-driver:
    build:
      context: ../Velo-identity-driver-service 
      dockerfile: Dockerfile
    container_name: velo-php-identity
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=velo-postgres
      - DB_PORT=5432
      - DB_DATABASE=velo_identity
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    volumes:
      - ../Velo-identity-driver-service:/var/www/html 
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - velo-postgres
    networks:
      - velo-network 

  # 4. MICROSERVIÇO TELEMETRY (Fastify Mock)
  tracking-telemetry-service:
    image: node:20-alpine
    container_name: velo-tracking-telemetry
    command: node -e "const http = require('http'); http.createServer((req, res) => res.end('Telemetry Mock Running')).listen(3000);"
    networks:
      - velo-network
    
# 5. MICROSERVIÇO PAYMENT FINANCE (Spring Boot Mock Corrigido)
  payment-finance-service:
    image: alpine:latest
    container_name: velo-payment-finance
    command: >
      sh -c "while true; do echo -e 'HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"status\":\"Payment Mock Running\"}' | nc -l -p 8080; done"
    networks:
      - velo-network

  # 6. MICROSERVIÇO REVIEW RATING (NestJS Mock)
  review-rating-service:
    image: node:20-alpine
    container_name: velo-review-rating
    command: node -e "const http = require('http'); http.createServer((req, res) => res.end('Review Mock Running')).listen(3000);"
    networks:
      - velo-network

  # 7. GATEWAY NGINX
  nginx-gateway:
    image: nginx:1.25-alpine
    container_name: velo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - trip-matching
      - identity-driver
      - tracking-telemetry-service
      - payment-finance-service
      - review-rating-service
    networks:
      - velo-network

volumes:
  velo-db-data:

networks:
  velo-network:
    driver: bridge