events {
    worker_connections 1024;
}

http {
    # Define o upstream apontando para o container do NestJS e a porta dele
    upstream trip_matching_backend {
        server velo-trip-matching:3000;
    }

    server {
        listen 80;
        server_name localhost;

        # Roteia todas as chamadas de API do Velo para o NestJS
        location /api/v1/ {
            proxy_pass http://trip_matching_backend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeout estendido para operações de matching complexas
            proxy_read_timeout 90;
            proxy_connect_timeout 90;
        }

        # Página de fallback ou status do Gateway
        location / {
            return 200 '{"status": "Velo API Gateway Online"}';
            add_header Content-Type application/json;
        }
    }
}